### ISSUE TITLE
Doesn't build with gir-to-d 0.14

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream-generator#61]
Build fails at:
```
[78/449] Compiling D object 'girbindings@sta/.._build_girepo_gio_DBusUtilities.d.o'.
FAILED: girbindings@sta/.._build_girepo_gio_DBusUtilities.d.o 
dmd  -Igirbindings@sta -I. -I../appstream-generator-0.7.0 -Igirepo -I../appstream-generator-0.7.0/girepo -color=on -wi -g  -of'girbindings@sta/.._build_girepo_gio_DBusUtilities.d.o' -c ../build/girepo/gio/DBusUtilities.d
../build/girepo/gio/DBusUtilities.d(297): Error: template instance `sliceNew!GValue` template `sliceNew` is not defined
```
Works with 0.13

**Comment by ximion** [comment]
Already resolved in 905ae8c8d1e9c2d62526d1ce6f5dbe292bee2733
There will be a new release tomorrow or today.
