### ISSUE TITLE
Build fails with LDC

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream-generator#26]
appstream-generator 0.6.0 fails to build with ldc 1.0

FAILED: asgen_test@exe/src_asgen_engine.d.o 
ldc2  '-Iasgen_test@exe' '-enable-color' '-I../appstream-generator-0.6.0' '-I.' '-Isrc/' '-I../appstream-generator-0.6.0/src/' '-Isrc/girepo/' '-I../appstream-generator-0.6.0/src/girepo/' '-I/usr/include/d/mustache-d/src' '-w' '-enable-inlining=false' '-unittest' '-g' '-O0' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '-I/usr/include/AppStream' '-I/usr/include/cairo' '-I/usr/include/pixman-1' '-I/usr/include/freetype2' '-I/usr/include/libpng16' '-I/usr/include/harfbuzz' '-I/usr/include/libdrm' '-I/usr/include/gdk-pixbuf-2.0' '-I/usr/include/librsvg-2.0' '-I/usr/include/pango-1.0'  -of 'asgen_test@exe/src_asgen_engine.d.o' -c ../appstream-generator-0.6.0/src/asgen/engine.d
../appstream-generator-0.6.0/src/asgen/engine.d(560): Error: no property 'clear' for type 'string[string]'
../appstream-generator-0.6.0/src/asgen/engine.d(561): Error: no property 'clear' for type 'ulong[string]'
